security:

    providers:
        in_memory:
            memory:
                users:
                    demo:
                        password: $2a$12$ZtlBvtio2Yfqe1wgCshddOF/g96I7kDRidMwtfYg8tEoGcxCGxEIu
                        roles: 'ROLE_USER'
                    admin:
                        password: $2a$12$w15kXPrV0wsjzGk9ZPKa9.XDomGqcK79IK/37edOvVWN9LNzxAwEi
                        roles: 'ROLE_ADMIN'
                        
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /login
                check_path: /login_check
            logout: true   
                
    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/create, roles: ROLE_ADMIN }  
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
